### ISSUE TITLE
Improve Unique ID Search Bar

### ISSUE THREAD

**Issue by caleb-james-smith** [FNAL-HCAL-Ph1Upgrade/HCAL-Phase-1-HB-Upgrade_database#12]
Improve Unique ID search bar.

Example for HB QIE card:
- Barcode = 0700001
- Unique ID = 0x70000000 0xEAA1FC70
- Search entry = EAA1FC

We should support more general searching to make it less confusing (not case sensitive):
- possible search entry = 0x70000000 0xEAA1FC70
- possible search entry = 0xEAA1FC70
- possible search entry = EAA1FC70
- possible search entry = EAA1FC

We could also make the search error page more useful and dynamic. It could display what the use should enter, as in "Did you mean this?"

**Comment by hep06** [comment]
Now Fixed!
