### ISSUE TITLE
Unique Barcodes

### ISSUE THREAD

**Issue by caleb-james-smith** [FNAL-HCAL-Ph1Upgrade/HCAL-Phase-1-HB-Upgrade_database#16]
- The barcodes for prototype cards are like this: 0799001, 0799002, 0799003.
- The barcodes for production cards are like this: 0700001, 0700002, 0700003.
- For certain functions (uploading, lookups, searching), the database assumes that the final three digits are the same. This means that cards 0799001 and 0700001 conflict.

We need to remove these assumptions.

**Comment by hep06** [comment]
Fixed with this commit: https://github.com/FNAL-HCAL-Ph1Upgrade/HCAL-Phase-1-HB-Upgrade_database/commit/29d057092fa0dd7a1d05b40b890b1d6762bddb01

**Comment by hep06** [comment]
Now fixed!
